controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotiqhande_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

robotiqhande_forward_position_controller:
  ros__parameters:
    joints:
      - joint_finger
    interface_name: position
